version: '3.8'

services:
  # Service MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projetdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Service Backend (Node.js)
  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: projetdb
    ports:
      - "3000:3000"
    volumes:
      - ./backend/server.js:/usr/src/app/server.js
    networks:
      - app-network

  # Service Frontend (Nginx)
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/html:/usr/share/nginx/html
    networks:
      - app-network

  # Service Adminer
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: 